package com.syncro.domain.usecase

import com.syncro.domain.model.SyncroItem
import com.syncro.domain.repository.TaskRepository
import java.time.LocalDate
import javax.inject.Inject

class SaveTaskUseCase @Inject constructor(
    private val repository: TaskRepository
) {
    suspend operator fun invoke(title: String, description: String, date: LocalDate, time: String) {
        val task = SyncroItem.Task(
            id = "0", // Auto-generated by Room
            title = title,
            time = time,
            isCompleted = false
        )
        repository.insertTask(task, description, date)
    }
}
